version: '2'
services:
  test:
    image: code-server
    build:
      context: .
      dockerfile: cypress.Dockerfile
      args:
        - GH_TOKEN
    command: "/source --auth none --disable-telemetry"
    container_name: vscodeCodeQlExtension
    ports:
      - "8080:8080"
    volumes:
      - .:/source